config/routes.rb
Rails.application.routes.draw do
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    session['filters'] ||= {}
    session['filters'].merge!(fiter_params)
    puts session.inspect
    @players = Player.includes(:team)
                      .then { search_by_name _1 }
                      .then { filter_by_team _1 }
                      .then { apply_order _1 }
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy!

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :team_id, :seasons)
    end

    def fiter_params
      params.permit(:name, :team_id, :column, :direction)
    end

    def search_by_name(scope)
      session['filters']['name'].present? ? scope.where("players.name like ?", "%#{session['filters']['name']}%") : scope
    end

    def apply_order(scope)
      scope.order(session['filters'].slice('column', 'direction').values.join(" "))
    end

    def filter_by_team(scope)
      puts "#{session['filters']['team_id']} ----- team id"
      session['filters']['team_id'].present? ? scope.where(team_id: session['filters']['team_id']) : scope
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  def sort_link(column:, label:)
    direction = column == session['filters']['column'] ? next_direction : 'asc'
    link_to label, players_path(column:, direction:),data: {turbo_action: "replace"}
  end

  def next_direction
    session['filters']['direction'] == 'desc' ? 'asc' : 'desc'
  end

  def show_sort_indicator_for(column)
    sort_indicator if session['filters']['column'] == column
  end

  def sort_indicator
    tag.span class: ['sort',"sort-#{session['filters']['direction']}"]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboRefreshSorting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
    <%= yield :head %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, class: "contents") do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :seasons %>
    <%= form.number_field :seasons, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= player.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Team:</strong>
    <%= player.team_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Seasons:</strong>
    <%= player.seasons %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this player", player, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this player", edit_player_path(player), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/players/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing player</h1>

  <%= render "form", player: @player %>

  <%= link_to "Show this player", @player, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to players", players_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/players/index.html.erb
<div class="max-w-7xl mx-auto mt-12">
  <div class="shadow overflow-hidden border-b border-gray-200 rounded">
    <div class="flex justify-end mb-1">
      <%= form_with url: players_path, method: :get,data: {controller: 'autoform', turbo_action: "replace", turbo_permanent: ""} do |f| %>
        <%= f.select :team_id, options_for_select(Team.all.pluck(:name, :id),session.dig('filters', 'team_id')),{include_blank: 'All teams'},class: 'border-blue-500 rounded',data: {action: "autoform#submit"} %>
        <%= f.text_field :name, placeholder: 'Search by name', value: params[:name], class: 'border border-blue-500 rounded p-2',data: {action: "autoform#submit"} %>
      <% end %>
    </div>
    <table class="min-w-full bg-white">
      <thead class="bg-gray-800 text-white">
        <tr>
          <th class="px-6 py-3 text-left text-sm uppercase font-semibold hover:cursor-pointer relative" id="players-name">
            <%= show_sort_indicator_for("name") %>
            <%= sort_link column: 'name',label: 'Name' %>
          </th>
          <th class="px-6 py-3 text-left text-sm uppercase font-semibold hover:cursor-pointer relative" id="players-team">
            <%= show_sort_indicator_for("teams.name") %>
            <%= sort_link column: 'teams.name',label: 'Team' %>
          </th>
          <th class="px-6 py-3 text-left text-sm uppercase font-semibold hover:cursor-pointer relative" id="players-seasons">
            <%= show_sort_indicator_for('seasons') %>
            <%= sort_link column: 'seasons',label: 'Seasons' %>
          </th>
        </tr>
      </thead>
      <tbody class="text-gray-700">
        <% @players.each do |player| %>
          <tr>
            <td class="px-6 py-3 text-left"><%= player.name %></td>
            <td class="px-6 py-3 text-left"><%= player.team.name %></td>
            <td class="px-6 py-3 text-left"><%= player.seasons %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/players/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New player</h1>

  <%= render "form", player: @player %>

  <%= link_to "Back to players", players_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/players/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @player %>

    <%= link_to "Edit this player", edit_player_path(@player), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this player", player_path(@player), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to players", players_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>